baseURL: ''
languageCode: 'en-us'
title: "Ahmad's Library" 
theme: PaperMod

socialIcons:
  - name: twitter
    url: "https://twitter.com/"
  - name: stackoverflow
    url: "https://stackoverflow.com"
  - name: github
    url: "https://github.com/"


# Site parameters
params:
  # Site Author
  author: Ahmad
  # Author biography
  bio: Computer Engineer
  # Site Description, used in HTML meat
  description: My Blog

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
